---
title: "Daylight"
output: html_document
---

```{r , include=FALSE}
knitr::opts_chunk$set(echo=FALSE, results='hide', message=FALSE, warning=FALSE)
```

# Suncalc: Daylight

```{r }
library(suncalc)
library(lubridate)
library(dplyr)
library(tidyr)
library(ggplot2)

current_dt = as.POSIXct(format(Sys.time()),tz="CET")
current_date = as.Date(Sys.Date(),tz="CET")
dates_in_2021 = seq.Date(from = dmy("01-01-2022"),to = dmy("31-12-2022"),by = "1 day")
```

## Aarhus: Next 14 Days

```{r}
seq_next_14 = 
  seq.Date(Sys.Date(),Sys.Date()+days(14),by = "1 day")

event_order = c("dawn", 
                "sunrise", 
                "sunriseEnd",
                "goldenHourEnd",
                "goldenHour",
                # "solarNoon", 
                "sunsetStart", 
                "sunset", 
                "dusk", 
                "night")
event_order.labels = c("Dawn", 
                "Sunrise", 
                "Sunrise End",
                "Morning Golden Hour Ends",
                "Evening Golden Hour Start",
                # "solarNoon", 
                "Sunset Starts", 
                "Sunset", 
                "Dusk", 
                "Night")
### Next Week
# df.dates.next_week =
  suncalc::getSunlightTimes(date = seq_next_14,
                            lat = 55.7715024,
                            lon = 12.4932282,
                            tz = "CET",
                            keep = event_order) %>% 
  gather(EventName,EventTime,dawn:night) %>% 
  dplyr::mutate(EventName=factor(EventName,levels=event_order,labels=event_order.labels)) %>% 
  ggplot(.,aes(y=date,x=EventName)) +
  geom_tile(aes(group=EventTime,fill=EventTime),color="white") +
  geom_text(aes(label=strftime(EventTime,format = "%H:%M:%S")),color="white",size=3) +
  theme_bw() +
  theme(legend.position = "null",
        axis.text.x = element_text(angle = 45, hjust=1)) +
  labs(x=NULL,y=NULL) +
  scale_y_date(date_breaks = "1 day",date_labels = "%A %d %b")

# Next Month
```

## Next 3 Months

```{r}

seq_next_3_months = 
  seq.Date(Sys.Date(),Sys.Date()+months(3),by = "1 day")

### Next Week
df.dates.next_3_months =
  suncalc::getSunlightTimes(date = seq_next_3_months,
                            lat = 56.1572,
                            lon = 10.2107,
                            tz = "CET",
                            keep = c("solarNoon", 
                                     "sunrise", 
                                     "sunset", 
                                     "sunriseEnd",
                                     "sunsetStart", 
                                     "dawn", 
                                     "dusk", 
                                     "nauticalDawn", 
                                     "nauticalDusk",
                                     "night", 
                                     "goldenHourEnd", 
                                     "goldenHour")) %>% 
  gather(EventName,EventTime,solarNoon:goldenHour) %>% 
  group_by(date) %>% 
  dplyr::mutate(EventTime=as.numeric(difftime(EventTime,ymd_hms(paste0(date," 00:00:00"),tz = "Europe/Copenhagen"),units = "hours")))

min_time = min(df.dates.next_3_months$EventTime,na.rm = T)
min_time = floor( min_time )

max_time = max(df.dates.next_3_months$EventTime,na.rm = T)
max_time = ceiling( max_time )

seq(min_time,max_time)

ggplot(df.dates.next_3_months,aes(x=date,y = EventTime)) +
  geom_line(aes(color=EventName)) +
  theme_bw() +
  scale_x_date(date_breaks = "7 days",date_labels = "%d %b") +
  theme(legend.position = "bottom") +
  geom_vline(xintercept = Sys.Date()) + 
  scale_y_continuous(breaks = seq(min_time,max_time),labels = paste0(seq(min_time,max_time) %% 24,":00")) +
  labs(x=NULL,y=NULL)

```

## 2022

```{r eval=TRUE, include=TRUE}
### 2021 Dates
df.dates_2021 =
  suncalc::getSunlightTimes(date = dates_in_2021,
                            lat = 56.1572,
                            lon = 10.2107,
                            tz = "CET",
                            keep = c("solarNoon", 
                                     "sunrise", 
                                     "sunset", 
                                     "sunriseEnd",
                                     "sunsetStart", 
                                     "dawn", 
                                     "dusk", 
                                     "nauticalDawn", 
                                     "nauticalDusk",
                                     "night", 
                                     "goldenHourEnd", 
                                     "goldenHour")) %>% 
  gather(EventName,EventTime,solarNoon:goldenHour) %>% 
  group_by(date) %>%
  dplyr::mutate(EventTime=as.numeric(difftime(EventTime,ymd_hms(paste0(date," 00:00:00"),tz = "Europe/Copenhagen"),units = "hours")))

min_time = min(df.dates_2021$EventTime,na.rm = T)
min_time = floor( min_time )

max_time = max(df.dates_2021$EventTime,na.rm = T)
max_time = ceiling( max_time )


ggplot(df.dates_2021,aes(x=date,y = EventTime)) +
  scale_x_date(date_breaks = "1 month",date_labels = "%b") +
  geom_point(aes(color=EventName)) +
  theme_bw()+
  theme(legend.position = "bottom") +
  geom_vline(xintercept = Sys.Date())  +
  scale_y_continuous(breaks = seq(min_time,max_time),labels = paste0(seq(min_time,max_time) %% 24,":00")) +
  labs(x=NULL,y=NULL)

```


## Change in daylight coming weeks

```{r eval=TRUE, include=TRUE}

### 2021 Dates
df.dates_2021 =
  suncalc::getSunlightTimes(date = dates_in_2021,
                            lat = 56.1572,
                            lon = 10.2107,
                            tz = "CET",
                            keep = c("solarNoon", 
                                     "sunrise", 
                                     "sunset", 
                                     "sunriseEnd",
                                     "sunsetStart", 
                                     "dawn", 
                                     "dusk", 
                                     "nauticalDawn", 
                                     "nauticalDusk",
                                     "night", 
                                     "goldenHourEnd", 
                                     "goldenHour")) %>% 
  gather(EventName,EventTime,solarNoon:goldenHour) %>% 
  filter(date>=Sys.Date()) %>% 
  filter(date<=Sys.Date()+months(1)) %>% 
  group_by(EventName) %>% 
  dplyr::mutate(StartTime=EventTime) %>% 
  dplyr::mutate(StartTime=ifelse(StartTime==min(EventTime),StartTime,NA)) %>% 
  tidyr::fill(StartTime) %>% 
  group_by(EventName) %>% 
  dplyr::mutate(StartTime=as.POSIXct(StartTime,origin="1970-01-01"),tz="CET") %>% 
  dplyr::mutate(StartTime=ymd_hms(paste0(year(EventTime),"-",month(EventTime),"-",day(EventTime)," ",hour(StartTime),":",minute(StartTime),":",second(StartTime)),tz="CET")) %>% 
  dplyr::mutate(EventTime=as.POSIXct(EventTime,tz="CET")) %>% 
dplyr::mutate(MinutesChanged=round(as.numeric(difftime(EventTime,StartTime,units="mins")),digits=2)) %>% 
  dplyr::mutate(DailyChange=MinutesChanged-lag(MinutesChanged))


ggplot(df.dates_2021,aes(x=date,y = MinutesChanged)) +
  scale_x_date(date_breaks = "3 days",date_labels = "%a %d") +
  geom_point(aes(color=EventName)) +
  theme_bw() +
  theme(legend.position = "bottom") +
  geom_vline(xintercept = Sys.Date())  +
  labs(x=NULL,y=NULL)


ggplot(df.dates_2021,aes(x=date,y = DailyChange)) +
  scale_x_date(date_breaks = "3 days",date_labels = "%a %d") +
  geom_line(aes(color=EventName)) +
  theme_bw() +
  theme(legend.position = "bottom") +
  geom_vline(xintercept = Sys.Date())  +
  labs(x=NULL,y=NULL)

```
