on:
  push:
     branches:
       - main
  schedule:
    - cron:  '10 12 * * *' # runs every day numbers are out at 14:10

name: when-can-we-bbq
# Yes
jobs:
  echokey:
    name: echo key
    #runs-on: macOS-latest
    runs-on: ubuntu-latest
    steps:
      - name: Echo API KEY
        #run: echo $APIKEY
        run: Rscript -e 'print(' + $APIKEY + ')' 
        env:
          APIKEY: ${{ secrets.APIKEY }}
