on:
  push:
     branches:
       - main
  schedule:
    - cron:  '10 12 * * *' # runs every day numbers are out at 14:10

name: when-can-we-bbq
# Yes
jobs:
  renderbook:
    name: Render Book
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@v1
      - name: Apt-get update
        run: sudo apt-get update
      - name: Set Environment Variables
        run: echo APIKEY="$APIKEY" >> ~/.Renviron
        env:
          APIKEY: ${{ secrets.APIKEY }}
      - name: Render Book
        run: Rscript -e 'bookdown::render_book("index.Rmd")'

