on:
  push:
     branches:
       - main
  schedule:
    - cron:  '10 12 * * *' # runs every day numbers are out at 14:10

name: when-can-we-bbq

jobs:
  renderbook:
    name: renderbook
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: R Package Dependencies 1
        run: sudo apt-get -y install libcurl4-gnutls-dev
      - name: R Package Dependencies 2
        run: sudo apt-get -y install xml2 openssl libxml2
      - name: Enable Rjava
        run: sudo R CMD javareconf
      - name: Install rvest
        run: Rscript -e 'install.packages(c("rvest"))'
      - name: Install Package - Suncalc
        run: Rscript -e 'install.packages(c("suncalc"))'
      - name: Install Packages - Bookdown
        run: Rscript -e 'install.packages(c("bookdown"))'
      - name: Install Packages - Lubridate
        run: Rscript -e 'install.packages(c("lubridate"))'
      - name: Install Packages - Dplyr
        run: Rscript -e 'install.packages(c("dplyr"))'
      - name: Install Packages - Tidyr
        run: Rscript -e 'install.packages(c("tidyr"))'
      - name: Install Packages - ggplot2
        run: Rscript -e 'install.packages(c("ggplot2"))'
      - name: Install Packages - httr
        run: Rscript -e 'install.packages(c("httr"))'
      - name: Install Packages - jsonlite
        run: Rscript -e 'install.packages(c("jsonlite"))'
      #- name: Install Packages - devtools
      #  run: Rscript -e 'install.packages(c("devtools"))'
      - name: Install weatherR
        run: Rscript -e 'install.packages("weatherr");'
      - name: Apt-get update
        run: sudo apt-get update
      - name: Set Environment Variables
        run: echo APIKEY="$APIKEY" >> ~/.Renviron
        env:
          APIKEY: ${{ secrets.APIKEY }}
      - name: Render Book
        run: Rscript -e 'bookdown::render_book("index.Rmd")'
      - uses: actions/upload-artifact@v1
        with:
          name: _book
          path: _book/

  checkout-and-deploy:
    runs-on: ubuntu-latest
    needs: renderbook
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: _book # optional
        path: _book # optional
    - name: Deploy to GitHub Pages
      uses: Cecilapp/GitHub-Pages-deploy@v3
      with:
        build_dir: _book/
        email: ${{ secrets.EMAIL }}
        jekyll: no                     
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        EMAIL: ${{ secrets.EMAIL }} 
        BUILD_DIR: _book/
